import "./globals.css";
import  { Metadata } from "next";
import { headers } from "next/headers";

import { cookieToInitialState } from "wagmi";

import { config } from "./walletconnet";
import Web3ModalProvider from "./index";

export const metadata = {
  title: "CFX with walletconnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider initialState={initialState}>
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}